### ISSUE TITLE
useEffect to clearTimeout dependency array?

### ISSUE THREAD

**Issue by crobinson42** [DrugoLebowski/use-throttled-callback#3]
Why is the hook not using the dependency array 2nd arg in `useEffect` here: https://github.com/DrugoLebowski/use-throttled-callback/blob/develop/src/use-throttled-callback.ts#L42

I think what you want is this:

```
useEffect(() => {
    return () => {
      clearTimeout(timeoutId.current)
    }
  }, [])
```

When you omit the 2nd arg in `useEffect`, you are clearing the timeout every time the hook is fired (including when components and parent components re-render)

**Comment by DrugoLebowski** [comment]
Hey @crobinson42. I have to be honest, I wrote this hook some time ago when my experience on React was not so high. Anyway, thanks to having pointed out that issue. I'll try to resolve it as soon as possible if you need it.
